### ISSUE TITLE
Using OpenID (Steam) provider

### ISSUE THREAD

**Issue by joercasey** [kasperisager/sails-generate-auth#138]
I'm having trouble plugging passport-steam into this framework. 

The reported error is:
```
C:\Users\Joe\testProject\node_modules\passport-steam\lib\passport-steam\strategy.js:67
            id: result.response.players[0].steamid,
                                          ^
TypeError: Cannot read property 'steamid' of undefined
    at steamapi.getPlayerSummaries.callback (C:\Users\Joe\testProject\node_modules\passport-steam\lib\passport-steam\strategy.js:67:43)
    at IncomingMessage.<anonymous> (C:\Users\Joe\testProject\node_modules\passport-steam\node_modules\steam-web\lib\steam.js:218:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

I have a feeling that this is caused by SteamWebAPI returning an empty response: `{"response":{"players":[]}}`, which is caused by a bogus SteamID in the request. The offending line is here in passport-steam: https://github.com/liamcurry/passport-steam/blob/master/lib/passport-steam/strategy.js#L53

Looking at `identifier` parameter to `getUserProfile`, it appears to be the entire Sails request scope. If I hardcode a good steam id into that array, I get this error:
```
C:\Users\Joe\testProject\api\services\passport.js:98
    return next(new Error('Neither a username nor email was available'));
           ^
TypeError: undefined is not a function
    at Authenticator.passport.connect (C:\Users\Joe\testProject\api\services\passport.js:98:12)
    at module.exports (C:\Users\Joe\testProject\api\services\protocols\openid.js:24:12)
    at steamapi.getPlayerSummaries.callback (C:\Users\Joe\testProject\node_modules\passport-steam\lib\passport-steam\strategy.js:72:11)
    at IncomingMessage.<anonymous> (C:\Users\Joe\testProject\node_modules\passport-steam\node_modules\steam-web\lib\steam.js:218:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```

I think that makes sense since the steam response doesn't have a username nor email, but this is the profile: ` {"emails":[{}],"name":{}}`

This is my passport configuration:
```javascript
steam: {
    name: 'Steam',
    protocol: 'openid',
    strategy: require('passport-steam').Strategy,
    options: {
      returnURL: 'http://localhost:1337/auth/steam/callback',
      realm: 'http://localhost:1337/',
      apiKey:'STEAM-API-KEY-REMOVED'
      }
    }
  }
```

Not sure if there is something simple I'm missing, or I need to write a ton of custom handling.

**Comment by kasperisager** [comment]
Sorry about the lack of response!

I honestly haven't tested the setup that extensively with OpenID providers but wouldn't be surprised if at least some custom code is required for handling scenarios like this. Did you ever come up with a solution?

**Comment by bORm** [comment]
+1

**Comment by joercasey** [comment]
The passport-steam npm code was not the most recent version, strangely. After manually updating the module, it worked. Here is the issue on their github: https://github.com/liamcurry/passport-steam/issues/10#issuecomment-82616490
