### ISSUE TITLE
Unable to login with existing credentials

### ISSUE THREAD

**Issue by karantir** [kasperisager/sails-generate-auth#159]
Hi.

I'm trying to implement basic auth support, using `passport-local` strategy. I've already made all preparations, described in `sails-generate-auth` readme, successfully registered new user with `/register` (i saw it in `req.session` after redirect and check my mongo backend to be sure), then i've logged out. Thats it, after then all my login attempts with registered credentials was failing.

I've found out, that the error occures during `passport.callback` execution and returns the following traceback:

    TypeError: Object #<Object> has no method 'isEmail'
    at Strategy.exports.login [as _verify] (/vagrant/api/services/protocols/local.js:132:27)
    at Strategy.authenticate (/vagrant/node_modules/passport-local/lib/strategy.js:88:12)
    at attempt (/vagrant/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/vagrant/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Authenticator.passport.callback (/vagrant/api/services/passport.js:250:40)
    at Authenticator.bound [as callback] (/usr/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.AuthController.callback (/vagrant/api/controllers/AuthController.js:154:14)
    at bound (/usr/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at routeTargetFnWrapper (/usr/lib/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/usr/lib/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/lib/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at pass (/usr/lib/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/usr/lib/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/usr/lib/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /usr/lib/node_modules/sails/lib/router/bind.js:187:7
    at /vagrant/api/policies/passport.js:32:7

I appreciate any clues about this issue, cause it seems i've stuck.
Thanks in advance!

P.S. Here is the packages i use:

    "sails": "~0.11.0",
    "sails-disk": "~0.10.0",
    "sails-mysql": "~0.10.0",
    "sails-mongo": "~0.10.0",
    "sails-generate-auth": "~0.2.0",
    "rc": "~0.5.0",
    "include-all": "~0.1.3",
    "ejs": "~0.8.4",
    "passport": "~0.2.1",
    "passport-local": "~1.0.0",
    "bcryptjs": "~2.1.0",
    "validator": "0.2.1"

**Comment by karantir** [comment]
Nevermind, just mistyped `validator` package version. Sorry for bothering.
