### ISSUE TITLE
Using passport-paypal-oauth

### ISSUE THREAD

**Issue by misterch0c** [kasperisager/sails-generate-auth#172]
I've been trying to use passport-paypal-oauth with your generator
This is the step I followed:
```
Added this in my passport.js file:
    paypal: {
    name: 'Paypal',
    protocol: 'oauth2',
    strategy: require('passport-paypal-oauth').OAuth2Strategy,
    options: {
      clientID: 'myId',
      clientSecret: 'mySecret'
    }
  }
```
Then I installed passport-paypal-oauth. 

I get this error
```
error: Bootstrap encountered an error: (see below)
error: TypeError: undefined is not a function
    at /home/unkn0wn/sails/betquiz-backend/api/services/passport.js:325:16
    at Array.forEach (native)
    at Authenticator.passport.loadStrategies (/home/unkn0wn/sails/betquiz-backend/api/services/passport.js:281:27)
    at Authenticator.bound [as loadStrategies] (/home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports.bootstrap (/home/unkn0wn/sails/betquiz-backend/config/bootstrap.js:13:26)
    at Sails.runBootstrap (/home/unkn0wn/sails/betquiz-backend/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Sails.initialize (/home/unkn0wn/sails/betquiz-backend/node_modules/sails/lib/app/private/initialize.js:48:9)
    at bound (/home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/async/lib/async.js:610:21
    at /home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/async/lib/async.js:249:17
    at iterate (/home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/async/lib/async.js:149:13)
    at /home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/async/lib/async.js:160:25
    at /home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/async/lib/async.js:251:21
    at /home/unkn0wn/sails/betquiz-backend/node_modules/sails/node_modules/async/lib/async.js:615:34
    at /home/unkn0wn/sails/betquiz-backend/node_modules/sails/lib/app/load.js:201:13

```
The line 325 is this one
      `self.use(new Strategy(options, self.protocols[protocol]));`

The strategy seems empty...
```
  { name: 'Paypal',
     protocol: 'oauth2',
     strategy: undefined,
     options: 
      { clientID: 'AV-pk7t1TboJdxoDvivxoIglqFGR2qcR_a1fUhXSr0KuXmv7nGJ_Fr5FCRtVqhxWl7XuDgBpt7WHd0a4',
        clientSecret: 'ENCx8QQRb-BEeIzz--sFnUIr60g-MAKEjgrkNRvCUrvgS00RmIAQGLEbgl5Z2pVQYq4iJCfhhAQZhm0U',
        callbackURL: 'http://localhost:3000/auth/paypal/callback' } },
```

I don't get the error if I use .Strategy instead of .Oauth2Strategy but it still doesn't work (and I guess I have to use.Oauth2 since it's Oauth2...)
Am I doing something wrong here?

Btw when I use . strategy I get redirected to

https://identity.x.com/xidentity/resources/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Fauth%2Fpaypal%2Fcallback&client_id=MYCLIENTID

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
