### ISSUE TITLE
login using sockets TypeError: Object #<MockIncomingMessage> has no method 'login'

### ISSUE THREAD

**Issue by blackbumer** [kasperisager/sails-generate-auth#99]
Hi. I followed read-me. I'm able to login using http web form but when i use sockets i get following error:
```js
io.socket.post('/auth/local', {identifier: "dan", password: "12345678", provider: "local"}, function(resData) {console.log(resData);})

/Users/danil/Developer/scoocoo/api/controllers/AuthController.js:159
      req.login(user, function (err) {
          ^
TypeError: Object #<MockIncomingMessage> has no method 'login'
    at /Users/danil/Developer/scoocoo/api/controllers/AuthController.js:159:11
    at Strategy.strategy.success (/Users/danil/Developer/scoocoo/node_modules/passport/lib/middleware/authenticate.js:194:18)
    at verified (/Users/danil/Developer/scoocoo/node_modules/passport-local/lib/strategy.js:83:10)
    at /Users/danil/Developer/scoocoo/api/services/protocols/local.js:171:20
    at /Users/danil/Developer/scoocoo/node_modules/bcryptjs/dist/bcrypt.js:219:13
    at /Users/danil/Developer/scoocoo/node_modules/bcryptjs/dist/bcrypt.js:1156:21
    at Object.next [as _onImmediate] (/Users/danil/Developer/scoocoo/node_modules/bcryptjs/dist/bcrypt.js:1036:21)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

I'd like to be able register and login using sockets only. Any suggestions?

**Comment by glebcha** [comment]
Faced the same issue. Anyone found the solution?

**Comment by kasperisager** [comment]
Closing as the project is no longer maintained.
